### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by weareblahs** [interlark/ustvgo_downloader#1]
When running the download.py script on Ubuntu, it returns with this:
  File "download.py", line 53
    print('[%d/%d] Successfully collected link for %s' % (item_n + 1, len(page_links), channel_list[item_n]), file=sys.stderr)
                                                                                                                  ^
SyntaxError: invalid syntax

**Comment by interlark** [comment]
It's python3 script. Please make sure you're using it.

**Comment by mentalhackz** [comment]
working perfect for me .. thank you for the hard work
