### ISSUE TITLE
Failed to collect link

### ISSUE THREAD

**Issue by EItanMao** [interlark/ustvgo_downloader#10]
Appears to be broken any chance for you to fix it?

**Comment by interlark** [comment]
It works for me, what's your issue?

**Comment by EItanMao** [comment]
I am getting the Failed to collect link for all the channels.

Will try and install again from scratch on a new VM.

What Linux distro are you working on?

**Comment by interlark** [comment]
Tested on Debian, Windows 10 - should be working, try to comment this line
https://github.com/interlark/ustvgo_downloader/blob/c460bd94622b6169d094f4fbbe4f5ccff8ee17f0/download.py#L22
which would turn off headless mode, so you can see what's going on.

**Comment by EItanMao** [comment]
Got it to work need to have libavcodec-extra installed maybe add it to the requerments.txt file?

**Comment by interlark** [comment]
Yeah, there have been several people with the same AVC codec issue. Probably, I should warn about it in readme, thanks.

**Comment by EItanMao** [comment]
One more question the Playlist file works fine now and same goes for the update script.

I am trying to integrate it into Tvheadend and because of its own limitations/the way it works need to get individual m3u8 files for each channel for example ABC.m3u8, AMC.m3u8 etc..

Any chance you update the two python scripts to allow this functionality?

THX

**Comment by interlark** [comment]
@EItanMao, I don't think I could bring that functionality into script, however
you can modify it as you wish. For per channel playlists you could write something following at the end of the download script
```python
    print('Generating ustvgo.m3u8 playlist...', file=sys.stderr)
    for name, url in video_links:
        with open(f'{name}.m3u8', 'w') as file:
            file.write('#EXTM3U\n\n')
            file.write('#EXTINF:-1,' + name + '\n')
            file.write("#EXTVLCOPT:http-user-agent=\"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0\"\n")
            file.write("#EXTVLCOPT:http-referrer=\"https://ustvgo.tv\"\n")
            file.write(url + '\n\n')
```
 Here's context file open and the loop through video links are swapped, so the playlists would be created per channel.

**Comment by interlark** [comment]
Readme updated. I'm closing it since the issues are solved.
