### ISSUE TITLE
cant play streams

### ISSUE THREAD

**Issue by milo123milo** [interlark/ustvgo_downloader#11]
Script is working well, i downloaded streams and updated token. But i cant play streams. VLC says "cant play mrl.." and if i try in browser is says "forbidden". Btw im using windows, i tried in ubuntu and android also but no luck. Any help, or the script is dead? Thanks

**Comment by milo123milo** [comment]
I did some tweaking and manage it to work on ubuntu. When i transfer the m3u8 file from ubuntu to windows it also works very well, but when i generate token in windows there is no chance i can make it work. Am i doing something wrong?

**Comment by milo123milo** [comment]
I tried VLC and MVP on win and it is not working with windows generated token.

**Comment by interlark** [comment]
So, you successfully update your token with update script and when you run ```vlc ustvgo.m3u8 --adaptive-use-access``` the stream is not playing, correct?
Also bear in mind that tokens are ip and time dependent things. I've checked it on Linux and Windows, everything's working fine.

**Comment by milo123milo** [comment]
On Linux everything is working very nice, the m3u8 list with updated token generated on linux is also working on windows, kodi and android. But, the m3u8 list generated on windows wont play anywhere. I concluded that the problem might be in tokens when i swapped token from list generated in linux to list generated in windows, because that way it works. Maybe am doing something wrong while generating list and token in windows? Thank you for being responsive, i thought i will never get answer on this! respect.

**Comment by interlark** [comment]
All that kinda tokens are usually generated from your ip address, server salt, date and period of time in which token get expired. You can try to decode your token, it's simply base64 string. And if you see something like ```server_time=11/29/2020 8:16:09 PM&hash_value=TApBDobC0zNCCT11rmFGyg==&validminutes=240``` then I assume your token is valid and problem is somewhere else.

Also you can open ustvgo site from your browser and search token among XHR requests to compare it with acquired one.

**Comment by interlark** [comment]
Hope that helped. Closing.
