### ISSUE TITLE
ERROR:  File SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by obreo** [interlark/ustvgo_downloader#6]
I get error whenever I run download.py using Pythin3

`File "download.py", line 38`
    `'http': f 'http://{PROXY}',`
                             `^`
`SyntaxError: invalid syntax`

Also I would like to ask, is it necessary to use a proxy to avoid Ban of Ip or it has other purposes ?

**Comment by interlark** [comment]
You are using python2, but this script requires python3 to run.
FYI, you don't have to download playlist, you can use existing one - just run [update.py](https://github.com/interlark/ustvgo_downloader/blob/master/update.py)

**Comment by interlark** [comment]
Proxy needs only to bypass region restrictions on the site, which blocks you from collecting the links. Once you've got all the links, you don't need proxy anymore.

**Comment by obreo** [comment]
Actually I tried using python3 on linux and it gives that error, and when I try python command on both of linux and windows the scrapping starts but keeps giving Trying and Filed for each channel

**Comment by interlark** [comment]
Hmm, I've tested it on python3.8 and python3.7, and for some reason python3.8 works fine, while python3.7 fails to lookup playlist request https://github.com/interlark/ustvgo_downloader/blob/7faf9a2422bb8f3eb95662645b74492013bba1a4/download.py#L81

Thanks for the report, now it works properly on both versions, try last commit.

**Comment by interlark** [comment]
Alright, eventually I figured out that the issue cased by different versions of upstream "selenium-wire" library, I specified version in [requirements.txt](https://github.com/interlark/ustvgo_downloader/blob/master/requirements.txt), just run
```bash
run pip3 install -r requirements.txt
```
to update library version.

**Comment by obreo** [comment]
Thank now the download.py and update.py are working well!
