### ISSUE TITLE
ReferenceError: vitag is not defined

### ISSUE THREAD

**Issue by cinema44** [interlark/ustvgo_downloader#8]
When I use download.py I always get errors in geckodriver.log like:
JavaScript error: https://ustvgo.tv/abc-live-streaming-free/, line 272: ReferenceError: vitag is not defined

Everything was done before as expected in readme. I'm using Linux Mint 18. Before I tried Ubuntu 20 and similar. Always the same result.

**Comment by interlark** [comment]
It should be working, try to comment this line
https://github.com/interlark/ustvgo_downloader/blob/c460bd94622b6169d094f4fbbe4f5ccff8ee17f0/download.py#L22
which would turn off headless mode, so you can see what's going on.
Maybe there's some sorta proxy on your end that transforms web pages for the sake of ad-blocking or something else.

**Comment by cinema44** [comment]
Thank you for that hint. The issue comes from privacy dialog from original page. Nobody press ‚accept‘ in headless mode.
