### ISSUE TITLE
Not working on server

### ISSUE THREAD

**Issue by dinandferro** [interlark/ustvgo_downloader#9]
The execution stays on loop with same errors everytime:

1603999502635   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "--headless" "-foreground" "-no-remote" "-pro$
*** You are running in headless mode.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1603999506047   Marionette      INFO    Listening on port 38058
1603999506187   Marionette      WARN    TLS certificate errors will be ignored for this session
1603999506192   Marionette      INFO    Proxy settings initialised: {"proxyType":"manual","httpProxy":"127.0.0.1:33875","noProxy":[],"sslProxy"$
JavaScript error: https://ustvgo.tv/gsn/, line 273: ReferenceError: vitag is not defined
1603999513401   Marionette      WARN    TimedPromise timed out after 500 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:228:19
TimedPromise@chrome://marionette/content/sync.js:213:10
interaction.flushEventLoop@chrome://marionette/content/interaction.js:418:10
webdriverClickElement@chrome://marionette/content/interaction.js:179:31
JavaScript error: https://ustvgo.tv/travel-channel-live-free/, line 272: ReferenceError: vitag is not defined
1603999526091   Marionette      WARN    TimedPromise timed out after 500 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:228:19
TimedPromise@chrome://marionette/content/sync.js:213:10
interaction.flushEventLoop@chrome://marionette/content/interaction.js:418:10
webdriverClickElement@chrome://marionette/content/interaction.js:179:31
JavaScript error: https://ustvgo.tv/sec-network/, line 272: ReferenceError: vitag is not defined
1603999538632   Marionette      WARN    TimedPromise timed out after 500 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:228:19
TimedPromise@chrome://marionette/content/sync.js:213:10
interaction.flushEventLoop@chrome://marionette/content/interaction.js:418:10
webdriverClickElement@chrome://marionette/content/interaction.js:179:31
JavaScript error: https://ustvgo.tv/msnbc/, line 276: ReferenceError: vitag is not defined
1603999551126   Marionette      WARN    TimedPromise timed out after 500 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:228:19
TimedPromise@chrome://marionette/content/sync.js:213:10
interaction.flushEventLoop@chrome://marionette/content/interaction.js:418:10
webdriverClickElement@chrome://marionette/content/interaction.js:179:31

**Comment by interlark** [comment]
You mean dedicated server without X server running? I would suggest you to take screenshot in that case by adding following line somewhere in the code
```python
    driver.save_screenshot(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'error_screenshot.png'))
```

**Comment by dinandferro** [comment]
Thank you for replying. By "somewhere" you mean anywhere?

**Comment by dinandferro** [comment]
![error_screenshot](https://user-images.githubusercontent.com/73667068/97642334-1f297700-1a02-11eb-8c03-fed5fd37f0de.png)
Here's a screenshot.

**Comment by interlark** [comment]
Seems like you don't have AVC codecs installed on your server, try install them with
```bash
sudo apt-get install ubuntu-restricted-extras
```
if you have ubuntu server installed or commonly
```bash
sudo apt-get install libavcodec58 libav-tools ffmpeg
```

**Comment by dinandferro** [comment]
Thank you very much! It worked with the first command. How do I delete this post?
